# Name of the GitHub Action workflow
name: Automated Daily Commit

on:
  # Schedule the workflow to run daily at 07:30 UTC
  # This uses a specific hour and minute as required.
  schedule:
    - cron: '30 7 * * *'

  # Allow the workflow to be triggered manually from the Actions tab
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    
    # Grant permissions for the job to write content to the repository
    permissions:
      contents: write

    steps:
      # Step 1: Check out the repository's code so the workflow can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Create or update a file to ensure a change exists for the commit.
      # The name of this step includes the required email address.
      - name: 23f3001368@ds.study.iitm.ac.in
        run: |
          echo "Last updated on $(date)" > daily-update.txt

      # Step 3: Configure Git, commit the change, and push it to the repository
      - name: Commit and push changes
        run: |
          # Configure git with the bot's identity
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Add the modified file to the staging area
          git add daily-update.txt
          
          # Commit the changes. The `|| exit 0` prevents the workflow from failing
          # if there are no changes to commit.
          git commit -m "Automated daily update" || exit 0
          
          # Push the commit to the main branch
          git push
